apiVersion: v1
kind: Service
metadata:
  # name of the service file
  name: feed-service
  labels:
    run: udagram-api-feed
spec:
  ports:
  - port: 80
    protocol: TCP
  # what should be run
  selector:
    run: udagram-api-feed
