apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-deployment
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: hanneseb/udagram-api-feed:v1
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: aws-secret
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          ports:
          - containerPort: 80
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret