apiVersion: v1
kind: Service
metadata:
  # name of the service file
  name: user-service
  labels:
    run: udagram-api-user
spec:
  ports:
  - port: 80
    protocol: TCP
  # what should be run
  selector:
    run: udagram-api-user
