apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-deployment
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: hanneseb/udagram-api-feed:v1
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: postgres_username
                optional: False
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: postgres_password
                optional: False
        ports:
        - containerPort: 80
