apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: hanneseb/udagram-frontend:v1
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: aws-secret
        - secretRef:
            name: env-secret
        ports:
        - containerPort: 80
